### ISSUE TITLE
New Continuous Integration Environment

### ISSUE THREAD

**Issue by cassar** [govhackaustralia/hackerspace3#219] opened 2020-10-10 05:05 UTC
## Background

A new environment is required before the move to continuous integraton.

## Tasks

- [ ] Create new `continuous-integration` environment that uses in memory [sqlite](https://www.sqlite.org/index.html) to run tests.

**Comment by mattcen** [comment] 2020-10-11 00:35
This is a duplicate of #218, right?

**Closed** 2020-10-11 03:01 UTC
Labels: enhancement
